# Generated by Django 3.2.9 on 2021-11-30 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211130_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='widgets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.widgets'),
        ),
    ]
