# Generated by Django 3.2.9 on 2021-12-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_userdata_widgets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='widgets',
            old_name='name',
            new_name='feature',
        ),
        migrations.RemoveField(
            model_name='widgets',
            name='description',
        ),
        migrations.RemoveField(
            model_name='widgets',
            name='params',
        ),
        migrations.AddField(
            model_name='widgets',
            name='services',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='widgets',
            name='url_api',
            field=models.URLField(default='none'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='widgets',
            name='clock',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='WidgetsParam',
        ),
    ]
