# Generated by Django 3.2.9 on 2021-12-01 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_userdata_widgets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='widgets',
            old_name='name',
            new_name='services',
        ),
        migrations.AlterField(
            model_name='widgets',
            name='clock',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='widgets',
            name='params',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.widgetsparam'),
        ),
    ]
