# Generated by Django 3.2.9 on 2021-12-01 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211201_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='widgets',
        ),
        migrations.AddField(
            model_name='widgets',
            name='widgets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userdata'),
        ),
    ]
