# Generated by Django 3.2.9 on 2021-12-01 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211201_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='widgets',
            old_name='widgets',
            new_name='userdata',
        ),
    ]
