# Generated by Django 3.2.9 on 2021-12-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_widgets_widgets_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widgets',
            name='url_api',
        ),
        migrations.AddField(
            model_name='widgets',
            name='params',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
